name: Build Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a file
        run: echo "This is my app build file" > app.txt

      - name: Read the file
        run: cat app.txt

      - name: Simulate build
        run: echo "Build completed successfully"
        
      - name: List files
        run: ls -l
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-file
          path: app.txt
